<?php

use PHPMailer\PHPMailer\PHPMailer;


$mail = new PHPMailer();


$mail->isSMTP();
$mail->Host = 'smtp.mailtrap.io';
$mail->SMTPAuth = true;
$mail->Username = '1a2b3c4d5e6f7g'; //paste one generated by Mailtrap
$mail->Password = '1a2b3c4d5e6f7g'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;
